"""Build the self-contained visual review; no catalog or approval mutations."""
import argparse, base64, hashlib, html, json
from pathlib import Path

def build(root):
    data=json.loads((root/'lote.json').read_text())
    def enc(path):
        p=root/path;mime='image/webp' if p.suffix=='.webp' else 'image/jpeg'
        return 'data:'+mime+';base64,'+base64.b64encode(p.read_bytes()).decode()
    e=html.escape;cards=[]
    for p in data['productos']:
        links=' · '.join('<a target="_blank" rel="noopener" href="'+e(x['url'])+'">Foto '+str(i+1)+'</a>' for i,x in enumerate(p['fuentes_identificacion']))
        cards.append(f'''<article id="{e(p['sku'])}"><div class="title"><div><small>{e(p['categoria'])} · {e(p['sku'])}</small><h2>{e(p['nombre'])}</h2></div><span class="status">{e(p['estado_revision'])}</span></div>
<div class="pair"><figure><figcaption>ANTES <span>{e(p['etiqueta_antes'])}</span></figcaption><img loading="lazy" alt="Antes {e(p['sku'])}" src="{enc(p['antes'])}"></figure><figure><figcaption>PROPUESTA PREMIUM <span>Sin publicar · edición asistida</span></figcaption><img loading="lazy" alt="Propuesta {e(p['sku'])}" src="{enc(p['vista'])}"></figure></div>
<div class="notes"><p><b>Fidelidad:</b> {e(p['fidelidad'])}</p><p><b>Derechos:</b> fotografía propia autorizada por CONECTATECH. Sin píxeles de fotografías externas.</p><p><b>Identificación:</b> {e(p['identificacion'])}</p><p><b>Clasificación comercial:</b> {e(p['tipo'])}. <b>Maestro:</b> 1254 × 1254 PNG. Las versiones de catálogo se generarán después de la aprobación.</p><p><b>Fuente de la imagen:</b> <a href="{e(p['fuente_imagen'])}" target="_blank" rel="noopener">Fotografía propia de Drive</a>. Todas las vistas: {links}.</p><p><b>Datos conservados:</b> contado ${p['precio_contado']:.2f} · PVP ${p['pvp']:.2f} · existencias del corte: {p['stock']}. <a href="{e(p['url_publica'])}" target="_blank" rel="noopener">Ficha actual</a>.</p></div></article>''')
    page='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CONECTATECH · Revisión premium 001</title><style>
*{box-sizing:border-box}body{margin:0;background:#f1f5f8;color:#152938;font:16px/1.55 system-ui,sans-serif}main{max-width:1360px;margin:auto;padding:36px 22px 70px}header{padding:22px 0 30px;border-bottom:3px solid #00996b}h1{font-size:clamp(30px,4vw,48px);line-height:1.12;margin:12px 0}h2{font-size:23px;line-height:1.3;margin:7px 0}small{color:#0766b6;font-weight:750;letter-spacing:.06em}p{margin:9px 0}.notice{background:#fff4d5;border-left:4px solid #bc8b21;padding:16px 20px;margin:22px 0}.title{display:flex;gap:20px;align-items:center;justify-content:space-between}.status{font-size:13px;border-radius:20px;background:#e4eef5;padding:7px 12px;white-space:nowrap}article{background:white;margin:28px 0;padding:24px;border:1px solid #dce5ed;border-radius:18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:18px}figure{margin:0;border:1px solid #e3e9ee;border-radius:12px;overflow:hidden}figcaption{font-size:13px;font-weight:800;padding:12px 16px;background:#f4f7fa}figcaption span{display:block;color:#526372;font-size:12px;font-weight:500}img{display:block;width:100%;aspect-ratio:1;object-fit:contain;background:white;cursor:zoom-in}.notes{padding-top:16px;font-size:14px;color:#334b5c}a{color:#0068ae}nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}nav a{padding:5px 10px;background:white;border:1px solid #d5e1eb;border-radius:7px;text-decoration:none}dialog{border:0;padding:12px;max-width:96vw;max-height:96vh;background:white;border-radius:12px}dialog::backdrop{background:#081d2bd9}dialog img{width:auto;max-width:90vw;max-height:86vh;aspect-ratio:auto;cursor:zoom-out}button{padding:9px 18px;border:1px solid #b1c1ce;border-radius:6px;background:white;cursor:pointer}footer{color:#516776;font-size:14px}@media(max-width:700px){main{padding:18px 10px}article{padding:12px}.title{display:block}.status{display:inline-block;margin-top:8px}.pair{grid-template-columns:1fr;gap:12px}h2{font-size:20px}.notes{font-size:13px}}
</style><main><header><small>CONECTATECH · LOTE PREMIUM 001</small><h1>La misma tecnología.<br>Una presentación más cuidada.</h1><p>Cinco propuestas grandes para comparar iluminación, encuadre y fidelidad. Esta revisión es independiente del diseño compacto del catálogo.</p><nav>'''+''.join('<a href="#'+p['sku']+'">'+p['sku']+'</a>' for p in data['productos'])+'''</nav></header><div class="notice"><b>Esperando aprobación visual. Ninguna de estas propuestas ha sustituido la imagen pública.</b><p>Cuatro comparaciones utilizan la fotografía actual del catálogo. AUDI028 todavía no tenía foto publicada: su «antes» es la fotografía propia recibida, indicada expresamente. Se priorizó material propio completo: los teléfonos siguen pendientes de imagen autorizada; los cargadores y baterías examinados no ofrecieron una vista completa suficiente.</p><p>Las propuestas usan edición asistida por IA. Se cotejaron los rasgos principales con las fotografías propias; MOUS039 y SOPO009 requieren revisar especialmente los microtextos y la textura superficial antes de considerarlos publicables. No se afirma recuperación de detalle óptico inexistente.</p></div>'''+''.join(cards)+'''<footer><p>Referencia visual inspeccionada: Reporte-visual-CONECTATECH(1).html — MOUS041, TECL028, CABL107, CARG070, POWE014 y AUDI108. Se reutilizó como referencia de composición e iluminación; no se reprodujeron sus fotografías externas.</p><p>Maestros, huellas, fuentes y pendientes guardados por SKU. Precios, stock, SKU, URLs y sitio público conservados. Haz clic en una fotografía para verla ampliada. Aprobar el estilo no autoriza cambiar características físicas.</p></footer></main><dialog id="zoom"><button autofocus onclick="this.parentElement.close()">Cerrar</button><img alt="Detalle de revisión"></dialog><script>document.querySelectorAll('figure img').forEach(im=>im.addEventListener('click',()=>{const d=document.querySelector('#zoom');d.querySelector('img').src=im.src;d.querySelector('img').alt=im.alt;d.showModal()}));document.querySelector('#zoom img').onclick=()=>document.querySelector('#zoom').close();</script></html>'''
    (root/'Comparativa-premium-CONECTATECH.html').write_text(page)
    return len(cards)

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('directorio');args=parser.parse_args();print(build(Path(args.directorio)))
